apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-react-app
  namespace: sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sample-react-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sample-react-app
    spec:
      containers:
      - name: sample-react-app
        image: yny.ocir.io/<OBJECT_STORAGE_NAMESPACE>/sample-react-app:latest
        ports:
        - containerPort: 3000
